spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080
            client-id: client-id
            client-secret: client-secret
            scope: profile, email